<?php
/**
 * EncodingType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ElasticEmail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ElasticEmail\Model;
use \ElasticEmail\ObjectSerializer;

/**
 * EncodingType Class Doc Comment
 *
 * @category Class
 * @description Encoding type for the email headers
 * @package  ElasticEmail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EncodingType
{
    /**
     * Possible values of this enum
     */
    public const USER_PROVIDED = 'UserProvided';

    public const NONE = 'None';

    public const RAW7BIT = 'Raw7bit';

    public const RAW8BIT = 'Raw8bit';

    public const QUOTED_PRINTABLE = 'QuotedPrintable';

    public const BASE64 = 'Base64';

    public const UUE = 'Uue';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::USER_PROVIDED,
            self::NONE,
            self::RAW7BIT,
            self::RAW8BIT,
            self::QUOTED_PRINTABLE,
            self::BASE64,
            self::UUE
        ];
    }
}


