<?php
/**
 * MessageCategory
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  ElasticEmail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ElasticEmail\Model;
use \ElasticEmail\ObjectSerializer;

/**
 * MessageCategory Class Doc Comment
 *
 * @category Class
 * @package  ElasticEmail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MessageCategory
{
    /**
     * Possible values of this enum
     */
    const UNKNOWN = 'Unknown';
    const IGNORE = 'Ignore';
    const SPAM = 'Spam';
    const BLACK_LISTED = 'BlackListed';
    const NO_MAILBOX = 'NoMailbox';
    const GREY_LISTED = 'GreyListed';
    const THROTTLED = 'Throttled';
    const TIMEOUT = 'Timeout';
    const CONNECTION_PROBLEM = 'ConnectionProblem';
    const SPF_PROBLEM = 'SPFProblem';
    const ACCOUNT_PROBLEM = 'AccountProblem';
    const DNS_PROBLEM = 'DNSProblem';
    const NOT_DELIVERED_CANCELLED = 'NotDeliveredCancelled';
    const CODE_ERROR = 'CodeError';
    const MANUAL_CANCEL = 'ManualCancel';
    const CONNECTION_TERMINATED = 'ConnectionTerminated';
    const NOT_DELIVERED = 'NotDelivered';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::IGNORE,
            self::SPAM,
            self::BLACK_LISTED,
            self::NO_MAILBOX,
            self::GREY_LISTED,
            self::THROTTLED,
            self::TIMEOUT,
            self::CONNECTION_PROBLEM,
            self::SPF_PROBLEM,
            self::ACCOUNT_PROBLEM,
            self::DNS_PROBLEM,
            self::NOT_DELIVERED_CANCELLED,
            self::CODE_ERROR,
            self::MANUAL_CANCEL,
            self::CONNECTION_TERMINATED,
            self::NOT_DELIVERED,
        ];
    }
}


