<?php
/**
 * WebhookCreatePayload
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ElasticEmail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target='_blank' href='https://app.elasticemail.com/marketing/settings/new/manage-api'>here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target='_blank' href='https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme'>here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ElasticEmail\Model;

use \ArrayAccess;
use \ElasticEmail\ObjectSerializer;

/**
 * WebhookCreatePayload Class Doc Comment
 *
 * @category Class
 * @description Create webhook payload
 * @package  ElasticEmail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class WebhookCreatePayload implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'WebhookCreatePayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'url' => 'string',
        'notify_once_per_email' => 'bool',
        'notification_for_sent' => 'bool',
        'notification_for_opened' => 'bool',
        'notification_for_clicked' => 'bool',
        'notification_for_unsubscribed' => 'bool',
        'notification_for_abuse_report' => 'bool',
        'notification_for_error' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => 'string',
        'url' => 'string',
        'notify_once_per_email' => 'boolean',
        'notification_for_sent' => 'boolean',
        'notification_for_opened' => 'boolean',
        'notification_for_clicked' => 'boolean',
        'notification_for_unsubscribed' => 'boolean',
        'notification_for_abuse_report' => 'boolean',
        'notification_for_error' => 'boolean'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'url' => false,
        'notify_once_per_email' => false,
        'notification_for_sent' => false,
        'notification_for_opened' => false,
        'notification_for_clicked' => false,
        'notification_for_unsubscribed' => false,
        'notification_for_abuse_report' => false,
        'notification_for_error' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'Name',
        'url' => 'URL',
        'notify_once_per_email' => 'NotifyOncePerEmail',
        'notification_for_sent' => 'NotificationForSent',
        'notification_for_opened' => 'NotificationForOpened',
        'notification_for_clicked' => 'NotificationForClicked',
        'notification_for_unsubscribed' => 'NotificationForUnsubscribed',
        'notification_for_abuse_report' => 'NotificationForAbuseReport',
        'notification_for_error' => 'NotificationForError'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'url' => 'setUrl',
        'notify_once_per_email' => 'setNotifyOncePerEmail',
        'notification_for_sent' => 'setNotificationForSent',
        'notification_for_opened' => 'setNotificationForOpened',
        'notification_for_clicked' => 'setNotificationForClicked',
        'notification_for_unsubscribed' => 'setNotificationForUnsubscribed',
        'notification_for_abuse_report' => 'setNotificationForAbuseReport',
        'notification_for_error' => 'setNotificationForError'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'url' => 'getUrl',
        'notify_once_per_email' => 'getNotifyOncePerEmail',
        'notification_for_sent' => 'getNotificationForSent',
        'notification_for_opened' => 'getNotificationForOpened',
        'notification_for_clicked' => 'getNotificationForClicked',
        'notification_for_unsubscribed' => 'getNotificationForUnsubscribed',
        'notification_for_abuse_report' => 'getNotificationForAbuseReport',
        'notification_for_error' => 'getNotificationForError'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('notify_once_per_email', $data ?? [], null);
        $this->setIfExists('notification_for_sent', $data ?? [], null);
        $this->setIfExists('notification_for_opened', $data ?? [], null);
        $this->setIfExists('notification_for_clicked', $data ?? [], null);
        $this->setIfExists('notification_for_unsubscribed', $data ?? [], null);
        $this->setIfExists('notification_for_abuse_report', $data ?? [], null);
        $this->setIfExists('notification_for_error', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Filename
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url URL of notification.
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets notify_once_per_email
     *
     * @return bool|null
     */
    public function getNotifyOncePerEmail()
    {
        return $this->container['notify_once_per_email'];
    }

    /**
     * Sets notify_once_per_email
     *
     * @param bool|null $notify_once_per_email notify_once_per_email
     *
     * @return self
     */
    public function setNotifyOncePerEmail($notify_once_per_email)
    {
        if (is_null($notify_once_per_email)) {
            throw new \InvalidArgumentException('non-nullable notify_once_per_email cannot be null');
        }
        $this->container['notify_once_per_email'] = $notify_once_per_email;

        return $this;
    }

    /**
     * Gets notification_for_sent
     *
     * @return bool|null
     */
    public function getNotificationForSent()
    {
        return $this->container['notification_for_sent'];
    }

    /**
     * Sets notification_for_sent
     *
     * @param bool|null $notification_for_sent notification_for_sent
     *
     * @return self
     */
    public function setNotificationForSent($notification_for_sent)
    {
        if (is_null($notification_for_sent)) {
            throw new \InvalidArgumentException('non-nullable notification_for_sent cannot be null');
        }
        $this->container['notification_for_sent'] = $notification_for_sent;

        return $this;
    }

    /**
     * Gets notification_for_opened
     *
     * @return bool|null
     */
    public function getNotificationForOpened()
    {
        return $this->container['notification_for_opened'];
    }

    /**
     * Sets notification_for_opened
     *
     * @param bool|null $notification_for_opened notification_for_opened
     *
     * @return self
     */
    public function setNotificationForOpened($notification_for_opened)
    {
        if (is_null($notification_for_opened)) {
            throw new \InvalidArgumentException('non-nullable notification_for_opened cannot be null');
        }
        $this->container['notification_for_opened'] = $notification_for_opened;

        return $this;
    }

    /**
     * Gets notification_for_clicked
     *
     * @return bool|null
     */
    public function getNotificationForClicked()
    {
        return $this->container['notification_for_clicked'];
    }

    /**
     * Sets notification_for_clicked
     *
     * @param bool|null $notification_for_clicked notification_for_clicked
     *
     * @return self
     */
    public function setNotificationForClicked($notification_for_clicked)
    {
        if (is_null($notification_for_clicked)) {
            throw new \InvalidArgumentException('non-nullable notification_for_clicked cannot be null');
        }
        $this->container['notification_for_clicked'] = $notification_for_clicked;

        return $this;
    }

    /**
     * Gets notification_for_unsubscribed
     *
     * @return bool|null
     */
    public function getNotificationForUnsubscribed()
    {
        return $this->container['notification_for_unsubscribed'];
    }

    /**
     * Sets notification_for_unsubscribed
     *
     * @param bool|null $notification_for_unsubscribed notification_for_unsubscribed
     *
     * @return self
     */
    public function setNotificationForUnsubscribed($notification_for_unsubscribed)
    {
        if (is_null($notification_for_unsubscribed)) {
            throw new \InvalidArgumentException('non-nullable notification_for_unsubscribed cannot be null');
        }
        $this->container['notification_for_unsubscribed'] = $notification_for_unsubscribed;

        return $this;
    }

    /**
     * Gets notification_for_abuse_report
     *
     * @return bool|null
     */
    public function getNotificationForAbuseReport()
    {
        return $this->container['notification_for_abuse_report'];
    }

    /**
     * Sets notification_for_abuse_report
     *
     * @param bool|null $notification_for_abuse_report notification_for_abuse_report
     *
     * @return self
     */
    public function setNotificationForAbuseReport($notification_for_abuse_report)
    {
        if (is_null($notification_for_abuse_report)) {
            throw new \InvalidArgumentException('non-nullable notification_for_abuse_report cannot be null');
        }
        $this->container['notification_for_abuse_report'] = $notification_for_abuse_report;

        return $this;
    }

    /**
     * Gets notification_for_error
     *
     * @return bool|null
     */
    public function getNotificationForError()
    {
        return $this->container['notification_for_error'];
    }

    /**
     * Sets notification_for_error
     *
     * @param bool|null $notification_for_error notification_for_error
     *
     * @return self
     */
    public function setNotificationForError($notification_for_error)
    {
        if (is_null($notification_for_error)) {
            throw new \InvalidArgumentException('non-nullable notification_for_error cannot be null');
        }
        $this->container['notification_for_error'] = $notification_for_error;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


