<?php
/**
 * VerificationsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ElasticEmail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ElasticEmail\Test\Api;

use \ElasticEmail\Configuration;
use \ElasticEmail\ApiException;
use \ElasticEmail\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * VerificationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  ElasticEmail
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VerificationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for verificationsByEmailDelete
     *
     * Delete Email Verification Result.
     *
     */
    public function testVerificationsByEmailDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verificationsByEmailGet
     *
     * Get Email Verification Result.
     *
     */
    public function testVerificationsByEmailGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verificationsByEmailPost
     *
     * Verify Email.
     *
     */
    public function testVerificationsByEmailPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verificationsFilesByIdDelete
     *
     * Delete File Verification Result.
     *
     */
    public function testVerificationsFilesByIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verificationsFilesByIdResultDownloadGet
     *
     * Download File Verification Result.
     *
     */
    public function testVerificationsFilesByIdResultDownloadGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verificationsFilesByIdResultGet
     *
     * Get Detailed File Verification Result.
     *
     */
    public function testVerificationsFilesByIdResultGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verificationsFilesByIdVerificationPost
     *
     * Start verification.
     *
     */
    public function testVerificationsFilesByIdVerificationPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verificationsFilesPost
     *
     * Upload File with Emails.
     *
     */
    public function testVerificationsFilesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verificationsFilesResultGet
     *
     * Get Files Verification Results.
     *
     */
    public function testVerificationsFilesResultGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verificationsGet
     *
     * Get Emails Verification Results.
     *
     */
    public function testVerificationsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
